### ISSUE TITLE
Problems for testing

### ISSUE THREAD

**Issue by pp00704831** [XJTU-CVLAB-LOWLEVEL/RNN-MBP#6]
Hello,

I test your model with the released checkpoints,  I rename the checkpoints as  'model_best.pth.tar'  and run by the following command:

'python test.py --data_root gopro_lmdb --dataset gopro_ds_lmdb --test_only --test_checkpoint ./model_best.pth.tar --model RNN-MBP'

However, I can not load the checkpoints successfully,  some errors (I list parts of them) come up as:

Missing key(s) in state_dict: "module.model.forward_encoder.skip_enc1.weight", "module.model.forward_encoder.skip_enc2.weight", "module.model.forward_encoder.skip_enc3.weight", "module.model.forward_encoder.skip_dec1.weight", "module.model.forward_encoder.skip_dec2.weight", "module.model.forward_encoder.skip_dec3.weight"

 Unexpected key(s) in state_dict: "module.model.ORSNet.orb1.body.0.CA.conv_du.0.weight", "module.model.ORSNet.orb1.body.0.CA.conv_du.2.weight", "module.model.ORSNet.orb1.body.0.body.0.weight", "module.model.ORSNet.orb1.body.0.body.1.weight", "

How can I fix it? 
Thank you very much!

**Comment by SGusu** [comment]
I have the same problem. May I ask how you solved it later?
